AD419.DataHelper.Web/Controllers/CFDANumsImportController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AD419.DataHelper.Web.Models;
using Excel;

namespace AD419.DataHelper.Web.Controllers
{
    public class CFDANumsImportController : SuperController
    {
        // GET: CFDANumsImport
        public ActionResult Index()
        {
            return View(DbContext.CFDANumImports.ToList());
        }

        // GET: CFDANumsImport/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CFDANumImport cFDANumImport = DbContext.CFDANumImports.Find(id);
            if (cFDANumImport == null)
            {
                return HttpNotFound();
            }
            return View(cFDANumImport);
        }

        // GET: CFDANumsImport/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CFDANumsImport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CFDANum")] CFDANumImport cFDANumImport)
        {
            if (ModelState.IsValid)
            {
                DbContext.CFDANumImports.Add(cFDANumImport);
                DbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cFDANumImport);
        }

        // GET: CFDANumsImport/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CFDANumImport cFDANumImport = DbContext.CFDANumImports.Find(id);
            if (cFDANumImport == null)
            {
                return HttpNotFound();
            }
            return View(cFDANumImport);
        }

        // POST: CFDANumsImport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CFDANum, ProgramTitle")] CFDANumImport cFDANumImport)
        {
            if (ModelState.IsValid)
            {
                DbContext.Entry(cFDANumImport).State = EntityState.Modified;
                DbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cFDANumImport);
        }

        // GET: CFDANumsImport/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CFDANumImport cFDANumImport = DbContext.CFDANumImports.Find(id);
            if (cFDANumImport == null)
            {
                return HttpNotFound();
            }
            return View(cFDANumImport);
        }

        [HttpPost, ActionName("DeleteAll")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAll()
        {
            //This works but doesn't reset the sequence number.
            //var all = from c in db.CFDANumImport select c;
            //db.CFDANumImport.RemoveRange(all);
            //db.SaveChanges();

            DbContext.Database.ExecuteSqlCommand("TRUNCATE TABLE CFDANumImport");

            return RedirectToAction("Index");
        }

        // POST: CFDANumsImport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CFDANumImport cFDANumImport = DbContext.CFDANumImports.Find(id);
            DbContext.CFDANumImports.Remove(cFDANumImport);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                DbContext.Dispose();
            }
            base.Dispose(disposing);
        }

                [AllowAnonymous]
        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> file)
        {
            var myFile = Request.Files[0];

            var cfdaNums = new List<CFDANumImport>();
            if (myFile != null)
            {
                var fileName = myFile.FileName;
                var excelReader = ExcelReaderFactory.CreateOpenXmlReader(myFile.InputStream);
                excelReader.IsFirstRowAsColumnNames = true;
                var result = excelReader.AsDataSet();
               
                TempData.Add("Message", "Now viewing \"" + fileName + "\".");
                excelReader.Close();

                cfdaNums.AddRange(from DataRow row in result.Tables[0].Rows select new CFDANumImport(row));

                // This works.  Would now like the user to have a chance to review upload first.
                //if (ModelState.IsValid)
                //{
                //    db.CesListImports.AddRange(cesEntries);
                //    db.SaveChanges();
                //}

                return View("Display", cfdaNums);
            }
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Save(List<CFDANumImport> cfdaNums)
        {
            if (cfdaNums != null)
            {
                // This works.  Would now like the user to have a chance to review upload first.
                if (ModelState.IsValid)
                {
                    DbContext.CFDANumImports.AddRange(cfdaNums);
                    DbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        public FileResult Download(string id)
        {
            const string filePathAndFilename = @"~\Sample_Forms\CfdaNumbersForImport.xlsx";
            const string contentType = "application/text";
            //Parameters to file are
            //1. The File Path on the File Server
            //2. The content type MIME type
            //3. The parameter for the file save by the browser
            return File(filePathAndFilename, contentType, "SampleCfdaNumbers.xlsx");
        }
    }
}

AD419.DataHelper.Web/Views/CFDANumsImport/Create.cshtml
@model AD419.DataHelper.Web.Models.CFDANumImport

@{
    ViewBag.Title = "Add CFDA Number";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create a new CFDA Number:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CFDANum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CFDANum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CFDANum, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CFDANum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AD419.DataHelper.Web/Views/CFDANumsImport/Delete.cshtml
@model AD419.DataHelper.Web.Models.CFDANumImport

@{
    ViewBag.Title = "Delete CFDA Number";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CFDA Number @Html.DisplayFor(model => model.CFDANum)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CFDANum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CFDANum)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.ProgramTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramTitle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AD419.DataHelper.Web/Views/CFDANumsImport/Details.cshtml
@model AD419.DataHelper.Web.Models.CFDANumImport

@{
    ViewBag.Title = "CFDA Number Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>CFDA Number @Html.DisplayFor(model => model.CFDANum):</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CFDANum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CFDANum)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.ProgramTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramTitle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AD419.DataHelper.Web/Views/CFDANumsImport/Display.cshtml
@model System.Collections.Generic.List<AD419.DataHelper.Web.Models.CFDANumImport>

@{

    ViewBag.Title = "View CFDA Numbers Excel File";
}


<h2>@ViewBag.Title</h2>

@Styles.Render("~/Content/DataTables-1.9.4/media/css/dataTables")

@section AdditionalScripts
{
    @Scripts.Render("~/bundles/datatables")

    <script type="text/javascript">
        $(function () {
            var oTable = $(".table").dataTable({
                "oLanguage": {
                    "sLengthMenu": 'Display <select>' +
                        '<option value="10">10</option>' +
                        '<option value="25">25</option>' +
                        '<option value="50">50</option>' +
                        '<option value="100">100</option>' +
                        '<option value="-1">All</option>' +
                        '</select> records'
                },
                "iDisplayLength": -1,
                "aaSorting": [[0, "asc"]], //Default sort on second column
                //"aoColumnDefs": [
                //    //{ 'bSortable': false, 'aTargets': [0, 5] } //Disables sort on icon columns
                //]
            }).makeEditable();
            var oTable2 = $('#IndexTable').dataTable({
                "bSort": false,
                "bPaginate": false,
                "bInfo":false
            });
            var oTable3 = $('#ConstraintTable').dataTable({
                "bSort": false,
                "bPaginate": false,
                "bInfo": false
            });

        });
    </script>
}

@*<style type="text/css">
        .table {
            margin: 4px;
            border-collapse: collapse;
            width: 300px;
        }

        .header {
            background-color: gray;
            font-weight: bold;
            color: #fff;
        }

        .table th, .table td {
            border: 1px solid black;
            padding: 5px;
        }
    </style>*@
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m[0].CFDANum)</th>
                <th>@Html.DisplayNameFor(m => m[0].ProgramTitle)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CFDANum</td>
                    <td>@item.ProgramTitle</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="form-horizontal">
    @using (Html.BeginForm("Save", "CFDANumsImport", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        for (var i = 0; i < Model.Count; i++)
        {
            @Html.HiddenFor(m => m[i].CFDANum)
            @Html.HiddenFor(m => m[i].ProgramTitle)
        }

        <p>
            If all looks good, you can upload the values to the database.<br />
            <i>Note: You can also edit the values once they have been saved.</i>
        </p>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save CFDA Numbers to Database" class="btn btn-default" />
            </div>
        </div>
    }
</div>

AD419.DataHelper.Web/Views/CFDANumsImport/Edit.cshtml
@model AD419.DataHelper.Web.Models.CFDANumImport

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editing CFDA Number @Html.DisplayFor(model => model.CFDANum):</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CFDANum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CFDANum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CFDANum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AD419.DataHelper.Web/Views/CFDANumsImport/Index.cshtml
@model IEnumerable<AD419.DataHelper.Web.Models.CFDANumImport>

@{
    ViewBag.Title = "Index - CFDA Numbers";
}

@Html.Partial("_CfdaNumsUpload")
<hr />
<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create", "CFDANumsImport", null, new { @class="btn btn-default" })
</p>

@if (Model.Count() != 0)
{
    using (Html.BeginForm("DeleteAll", "CFDANumsImport", FormMethod.Post, new { id = "deleteForm" }))
    {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" id="btnDeleteAll" value="Delete All" title="Delete All" class="btn btn-default" onclick="return confirm('Are you sure you want to delete ALL the records?')" />
        </p>
    }

    <table id="cfdaImportTable" class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CFDANum)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProgramTitle)
                </th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CFDANum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProgramTitle)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4>CFDA Numbers Data has yet to be created or uploaded.</h4>
    <p>Select the "Create New" (above) or browse and display an existing CFDA Numbers Excel file (above).</p>
}

@section AdditionalScripts
{
    <script>
        $(function() {
            $('#cfdaImportTable').DataTable({
                columnDefs: [
                    { targets: [-1, -2, -3], sortable: false }
                ]
            });
        })
    </script>
}

AD419.DataHelper.Web/Views/CFDANumsImport/_CfdaNumsUpload.cshtml
<div>
    @using (Html.BeginForm("Upload", "CFDANumsImport", FormMethod.Post, new { id = "UploadForm", enctype = "multipart/form-data" }))
    {
        <div>
            <h4>Upload a CFDA Numbers Excel file:</h4>
            <i>Please ensure your spreadsheet has the following column names as illustrated below: (Note Only the CFDANum and ProgramTitle columns are actually needed.)</i>
            <p><i>Select <a href="~/CFDANumsImport/Download" class="btn btn-link">here</a> to download a sample form.</i></p>
            <img src="/Content/Images/CFDANumsExample.PNG" alt="CFDA Num Excel upload file example" width="1100">
        </div>
        <br />
        <b>Please select an CFDA Numbers Excel file to display:</b><input type="file" id="FileUpload1" name="FileUpload1" required="required" />
        <br />
        <input type="submit" value="Display CFDA Numbers" title="Upload" class="btn btn-default"/>
    }
</div>
