AD419.DataHelper.Web/Controllers/FieldStationExpensesImportController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AD419.DataHelper.Web.Helpers;
using AD419.DataHelper.Web.Models;
using AD419.DataHelper.Web.Services;
using ExcelDataReader;

namespace AD419.DataHelper.Web.Controllers
{
    public class FieldStationExpensesImportController : SuperController
    {
        private readonly FieldStationExpenseService _fieldStationExpenseService;

        public FieldStationExpensesImportController()
        {
            _fieldStationExpenseService = new FieldStationExpenseService(DbContext, FiscalYearService.FiscalEndDate);
        }

        // GET: FieldStationExpensesImport
        public ActionResult Index()
        {
            var stations = DbContext.FieldStationExpenseListImports.ToList();
            return View(stations);
        }

        // GET: FieldStationExpensesImport/Details/5
        public ActionResult Details(int id)
        {
            var station = DbContext.FieldStationExpenseListImports.Find(id);
            if (station == null)
            {
                return HttpNotFound();
            }

            return View(station);
        }

        // GET: FieldStationExpensesImport/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FieldStationExpensesImport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ProjectAccessionNum,FieldStationCharge,ProjectDirector")] FieldStationExpenseListImport fieldStationExpenseListImport)
        {
            if (!ModelState.IsValid) return View(fieldStationExpenseListImport);

            DbContext.FieldStationExpenseListImports.Add(fieldStationExpenseListImport);
            DbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: FieldStationExpensesImport/Edit/5
        public ActionResult Edit(int id)
        {
            var station = DbContext.FieldStationExpenseListImports.Find(id);
            if (station == null)
            {
                return HttpNotFound();
            }
            return View(station);
        }

        // POST: FieldStationExpensesImport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ProjectAccessionNum,FieldStationCharge,ProjectDirector")] FieldStationExpenseListImport fieldStationExpenseListImport)
        {
            if (!ModelState.IsValid) return View(fieldStationExpenseListImport);

            DbContext.Entry(fieldStationExpenseListImport).State = EntityState.Modified;
            DbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: FieldStationExpensesImport/Delete/5
        public ActionResult Delete(int id)
        {
            var station = DbContext.FieldStationExpenseListImports.Find(id);
            if (station == null)
            {
                return HttpNotFound();
            }

            return View(station);
        }

        [HttpPost, ActionName("DeleteAll")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAll()
        {
            // This works, but does not reset the sequence number back to the beginning.
            //var all = from c in db.FieldStationExpenseListImports select c;
            //db.FieldStationExpenseListImports.RemoveRange(all);
            //db.SaveChanges();

            DbContext.Database.ExecuteSqlCommand("TRUNCATE TABLE FieldStationExpenseListImport");

            //DbContext.Database.ExecuteSqlCommand("Update ProcessStatus " +
            //                                     "Set IsCompleted = 0  " +
            //                                     "Where Id = " + ProcessStatuses.ImportFieldStationExpenses);

            // 1. Use the hard-coded status Id to reset ProcessStatus.IsCompleted.
            DbContext.ClearStatusCompleted(ProcessStatuses.ImportFieldStationExpenses);
           
            // 2. Get it's categoryID and reset ProcessCategory.IsCompleted to false.

            //DbContext.Database.ExecuteSqlCommand("Update ProcessCategory " +
            //                                     "Set IsCompleted = 0 " +
            //                                     "From ProcessCategory t1 " +
            //                                     "Inner Join ProcessStatus t2 ON t1.Id = t2.CategoryId " +
            //                                     "Where t2.Id = " + ProcessStatuses.ImportFieldStationExpenses);

             DbContext.ClearCategoryCompleted(ProcessStatuses.ImportFieldStationExpenses);

             DbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        // POST: FieldStationExpensesImport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var station = DbContext.FieldStationExpenseListImports.Find(id);
            if (station == null)
            {
                return HttpNotFound();
            }

            DbContext.FieldStationExpenseListImports.Remove(station);
            DbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> file)
        {
            var myFile = Request.Files[0];
            if (myFile == null) return RedirectToAction("Index");

            var fileName = myFile.FileName;

            // setup reader:
            var excelReader = ExcelReaderFactory.CreateOpenXmlReader(myFile.InputStream);

            // read data:
            var result = excelReader.AsDataSet(new ExcelDataSetConfiguration()
            {
                ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
                {
                    UseHeaderRow = true
                }
            });
            excelReader.Close();

            // transform:
            var fieldStationExpenses = _fieldStationExpenseService.GetFieldStationsExpensesFromRows(result.Tables[0].Rows).ToList();

            // validate:
            var errors = new List<ModelStateDictionary>();
            foreach (var fieldStationExpense in fieldStationExpenses)
            {
                // clear and check
                ModelState.Clear();
                TryValidateModel(fieldStationExpense);

                if ( !fieldStationExpense.IsCurrentAd419Project)
                {
                    ModelState.AddModelError("IsCurrentAd419Project", "This expense is not assigned to an active project.");
                }

                // copy out errors
                var state = new ModelStateDictionary();
                state.Merge(ModelState);
                errors.Add(state);
            }
            ViewBag.Errors = errors;

            //TempData.Add("Message", "Now viewing \"" + fileName + "\".");

            return PartialView("_UploadData", fieldStationExpenses);
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Save(List<FieldStationExpenseListImport> fieldStationExpenseEntries)
        {
            if (fieldStationExpenseEntries != null)
            {
                // This works.  Would now like the user to have a chance to review upload first.
                if (ModelState.IsValid && fieldStationExpenseEntries.All(f => f.IsCurrentAd419Project))
                {
                    DbContext.FieldStationExpenseListImports.AddRange(fieldStationExpenseEntries);
                    DbContext.MarkStatusCompleted(ProcessStatuses.ImportFieldStationExpenses);
                    DbContext.MarkCategoryCompleted(ProcessStatuses.ImportFieldStationExpenses);

                    // We also need to clear the next category and process so that they 
                    // can be re-inserted in the expenses table as the new values.
                    DbContext.ClearStatusCompletedForNextCategory(ProcessStatuses.ImportFieldStationExpenses);
                    DbContext.ClearCategoryCompletedForNextCategory(ProcessStatuses.ImportFieldStationExpenses);

                    DbContext.SaveChanges();
                }
                else
                {
                    ErrorMessage = string.Format("ERROR! Your import file could not be saved.  It contained {0} records with expired projects that could not be automatically remapped.  Please make corrections and try again.", fieldStationExpenseEntries.Count(f => f.IsCurrentAd419Project == false));
                }
            }
            return RedirectToAction("Index");
        }
    }
}

AD419.DataHelper.Web/Views/FieldStationExpensesImport/Create.cshtml
@model AD419.DataHelper.Web.Models.FieldStationExpenseListImport
@{

    ViewBag.Title = "Create Field Station Expense";
}

<h2>@ViewBag.Title</h2>

    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Field Station Expense</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectAccessionNum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProjectAccessionNum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProjectAccessionNum, "", new { @class = "text-danger" })
                </div>
            </div>
        
            <div class="form-group">
                @Html.LabelFor(model => model.FieldStationCharge, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FieldStationCharge, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FieldStationCharge, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

AD419.DataHelper.Web/Views/FieldStationExpensesImport/Delete.cshtml
@model AD419.DataHelper.Web.Models.FieldStationExpenseListImport

@{

    ViewBag.Title = "Delete Field Station Expense";
}

<h2>@ViewBag.Title</h2>

    <h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.ProjectAccessionNum)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectAccessionNum)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.ProjectAccessionNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FieldStationCharge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FieldStationCharge)
        </dd>
    
    </dl>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AD419.DataHelper.Web/Views/FieldStationExpensesImport/Details.cshtml
@model AD419.DataHelper.Web.Models.FieldStationExpenseListImport
@{

    ViewBag.Title = "Field Station Expense Details";
}

<h2>@ViewBag.Title</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProjectAccessionNum)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ProjectAccessionNum)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FieldStationCharge)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FieldStationCharge)
            </dd>

    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>


AD419.DataHelper.Web/Views/FieldStationExpensesImport/Display.cshtml
@model List<AD419.DataHelper.Web.Models.FieldStationExpenseListImport>
@{

    ViewBag.Title = "View Field Station Expenses Excel File";
}


<h2>@ViewBag.Title</h2>

@Styles.Render("~/Content/DataTables-1.9.4/media/css/dataTables")

@section AdditionalScripts
{
    @Scripts.Render("~/bundles/datatables")

    <script type="text/javascript">
        $(function () {
            var oTable = $(".table").dataTable({
                "oLanguage": {
                    "sLengthMenu": 'Display <select>' +
                        '<option value="10">10</option>' +
                        '<option value="25">25</option>' +
                        '<option value="50">50</option>' +
                        '<option value="100">100</option>' +
                        '<option value="-1">All</option>' +
                        '</select> records'
                },
                "iDisplayLength": -1,
                "aaSorting": [[0, "asc"]], //Default sort on second column
                //"aoColumnDefs": [
                //    //{ 'bSortable': false, 'aTargets': [0, 5] } //Disables sort on icon columns
                //]
            }).makeEditable();
            var oTable2 = $('#IndexTable').dataTable({
                "bSort": false,
                "bPaginate": false,
                "bInfo":false
            });
            var oTable3 = $('#ConstraintTable').dataTable({
                "bSort": false,
                "bPaginate": false,
                "bInfo": false
            });

        });
    </script>
}

@*<style type="text/css">
        .table {
            margin: 4px;
            border-collapse: collapse;
            width: 300px;
        }

        .header {
            background-color: gray;
            font-weight: bold;
            color: #fff;
        }

        .table th, .table td {
            border: 1px solid black;
            padding: 5px;
        }
    </style>*@
<div>
    @Html.Partial("_UploadData", Model)

@*<table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(m => m[0].ProjectAccessionNum)</th>
                    <th>@Html.DisplayNameFor(m => m[0].FieldStationCharge)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ProjectAccessionNum</td>
                        <td>@item.FieldStationCharge</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="form-horizontal">
        @using (Html.BeginForm("Save", "FieldStationExpensesImport", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            for (var i = 0; i < Model.Count; i++)
            {
                @Html.HiddenFor(m => m[i].ProjectAccessionNum)
                @Html.HiddenFor(m => m[i].FieldStationCharge)
            }

            <p>If all looks good, you can upload the values to the database.<br/>
            <i>Note: You can also edit the values once they have been saved.</i></p>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save Field Station Expenses to Database" class="btn btn-default" />
                </div>
    </div>
        } *@
    </div>
   

AD419.DataHelper.Web/Views/FieldStationExpensesImport/Edit.cshtml
@model AD419.DataHelper.Web.Models.FieldStationExpenseListImport

@{

    ViewBag.Title = "Edit Field Station Expense";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectAccessionNum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProjectAccessionNum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProjectAccessionNum, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FieldStationCharge, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FieldStationCharge, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FieldStationCharge, "", new { @class = "text-danger" })
                </div>
            </div>

    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

AD419.DataHelper.Web/Views/FieldStationExpensesImport/Index.cshtml
@model IEnumerable<AD419.DataHelper.Web.Models.FieldStationExpenseListImport>

@{
    ViewBag.Title = "Field Station Expenses";
}

<div class="pull-right">
    <button class="btn btn-default display-inline" data-toggle="modal" data-target="#uploadModal"><i class="fa fa-upload"></i> Upload New Source File</button>
    <form action="@Url.Action("DeleteAll")" method="POST" class="display-inline">
        @Html.AntiForgeryToken()
        <input type="submit" id="btnDeleteAll" value="Delete All" title="Delete All" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete ALL the records?')"/>
    </form>
</div>

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Create New", "Create", "FieldStationExpensesImport", null, new { @class="btn btn-default" })
</p>

@if (Model.Count() != 0)
{
    @Html.Partial("_FieldStationExpensesTable", Model)
}
else
{
    <h4>Field Station Expenses Data has yet to be created or uploaded.</h4>
    <p>Select the "Create New" (above) or browse and display an existing Field Station Expenses Excel file (above).</p>
}

@Html.Partial("_Upload")

@section AdditionalScripts
{
    <script type="text/javascript" src="~/Scripts/upload-wizard.js"></script>
    <script type="text/javascript">
        $(function () {
            UploadWizard.setup({
                uploadUrl: '@Url.Action("Upload")',
                tableOptions: {
                    order: [[0, "desc"]]
                }
            });

            $('#uploadModal').on('hidden.bs.modal', UploadWizard.reset);
        });
        $(function () {
            $('#fieldImportTable').DataTable({
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
                columnDefs: [
                    { targets: [-1, -2, -3], sortable: false }
                ]
            });
        });
    </script>
}

AD419.DataHelper.Web/Views/FieldStationExpensesImport/_FieldStationExpensesUpload.cshtml
<div class="modal fade" id="uploadModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload a Field Station Expenses Excel file</h4>
            </div>
            <div class="modal-image">
                <img src="~/Content/Images/FieldStationExpensesExample.png" alt="Field Station Expenses Excel upload file example">
            </div>
            @using (Html.BeginForm("Upload", "FieldStationExpensesImport", FormMethod.Post, new { id = "UploadForm", enctype = "multipart/form-data", @class = "" }))
            {
                <div class="modal-body">
                    <p>
                        Please ensure your spreadsheet has the column names as illustrated above.<br />
                        Note that ProjectAccessionNum will automatically have leading zero(s) added.<br />
                        Download a sample form <a href="~/Content/Sample_Forms/ModifiedFieldStationExpensesForImport.xlsx">HERE <i class="fa fa-download"></i></a>
                    </p>
                    <div class="form-group">
                        <label class="control-label">Please select an Field Station Expenses Excel file to display:</label>
                        <input type="file" id="FileUpload1" name="FileUpload1" class="" required />
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-default" value="Upload" />
                </div>
            }
        </div>
    </div>
</div>

AD419.DataHelper.Web/Views/FieldStationExpensesImport/_Upload.cshtml
<div class="modal fade" id="uploadModal">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload a Field Station Expenses Excel file</h4>
            </div>

            <ul id="uploadTabs" class="step-progressbar">
                <li id="uploadStepper" class="active">
                    <h2>Upload</h2>
                </li>
                <li id="reviewStepper">
                    <h2>Review</h2>
                </li>
                <li id="confirmStepper">
                    <h2>Confirm</h2>
                </li>
            </ul>

            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="uploadTab">
                    <div class="modal-image">
                        <img src="~/Content/Images/FieldStationExpensesExample.png" alt="Field Station Expenses Excel upload file example">
                    </div>
                    <form id="uploadForm" enctype="multipart/form-data" class="">
                        @Html.AntiForgeryToken()
                        <div class="modal-body">
                            <p>
                                Please ensure your spreadsheet has the column names as illustrated above.<br />
                                Note that ProjectAccessionNum will automatically have leading zero(s) added.<br />
                                Download a sample form <a href="~/Content/Sample_Forms/ModifiedFieldStationExpensesForImport.xlsx">HERE <i class="fa fa-download"></i></a>
                            </p>
                            <div class="form-group">
                                <label class="control-label">Please select an Field Station Expenses Excel file to display:</label>
                                <input type="file" id="file" name="file" class="" required/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" class="btn btn-default" value="Process"/>
                        </div>
                    </form>
                </div>
                <div class="tab-pane" id="loadingTab">
                    <div class="loader text-center">
                        <i class="fa fa-spinner fa-spin fa-fw"></i>
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <div class="tab-pane" id="errorTab">
                    <div class="modal-body">
                        <div class="alert alert-danger" role="alert">
                            Something has gone terribly wrong. Are you sure you uploaded a proper file?
                        </div>
                    </div>
                    <div class="modal-footer text-left">
                        <div class="flex-between">
                            <button id="resetErrorButton" class="btn btn-danger"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</button>
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="reviewTab">
                    <div class="modal-body" id="review"></div>
                    <div class="modal-footer">
                        <div class="flex-between">
                            <button id="returnUploadButton" class="btn btn-danger"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</button>
                            <button id="continueConfirmButton" class="btn btn-default">Confirm and Upload <i class="fa fa-chevron-right" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="confirmTab">
                    <div class="modal-body text-center">
                        <p>
                            If everything looked good, you can upload the values to the database.<br />
                            <br />
                            <i>Note: You can also edit the values once they have been saved.</i>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <div class="flex-between">
                            <button id="returnReviewButton" class="btn btn-danger"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</button>
                            <button id="confirmButton" class="btn btn-default">Save to Database</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

AD419.DataHelper.Web/Views/FieldStationExpensesImport/_fieldStationExpensesTable.cshtml
@model IEnumerable<AD419.DataHelper.Web.Models.FieldStationExpenseListImport>

<table id="fieldStationExpensesTable" class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectAccessionNum)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ProjectNumber)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.FieldStationCharge)
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectAccessionNum)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.ProjectNumber)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.FieldStationCharge)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.Id})
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.Id})
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            </td>
        </tr>
    }
    </tbody>
</table>

AD419.DataHelper.Web/Views/FieldStationExpensesImport/_uploadData.cshtml
@model List<AD419.DataHelper.Web.Models.FieldStationExpenseListImport>

@{
    var errors = ViewBag.Errors as List<ModelStateDictionary> ?? Model.Select(m => new ModelStateDictionary()).ToList();
}

<table id="uploadTable" class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(x => Model[0].ProjectAccessionNum)
            </th>
            <th>
                @Html.DisplayNameFor(x => Model[0].ProjectNumber)
            </th>
            <th>
                @Html.DisplayNameFor(x => Model[0].FieldStationCharge)
            </th>
            <th>
                @Html.DisplayNameFor(x => Model[0].IsCurrentAd419Project)
            </th>
            <th>
                @Html.DisplayNameFor(x => Model[0].Message)
            </th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Count; i++)
        {
            var item = Model[i];
            var error = errors[i];
            <tr>
                <td>
                    @if (!error.IsValid)
                    {
                        var message = string.Join("\n",
                            error.Values
                                .SelectMany(v => v.Errors)
                                .Select(e => e.ErrorMessage));
                        
                        <span class="text-danger" title="@message">
                            <i class="fa fa-exclamation-triangle"></i>
                        </span>
                    }
                </td>
                <td>
                    @Html.DisplayFor(x => item.ProjectAccessionNum)
                </td>
                <td>
                    @Html.DisplayFor(x => item.ProjectNumber)
                </td>
                <td>
                    @Html.DisplayFor(x => item.FieldStationCharge)
                </td>
                <td>
                    @Html.DisplayFor(x => item.IsCurrentAd419Project)
                </td>
                <td>
                    @Html.DisplayFor(x => item.Message)
                </td>
            </tr>
        }
    </tbody>
</table>

<form id="confirmForm" method="POST" action="@Url.Action("Save")">
    @Html.AntiForgeryToken()
    @for (var i = 0; i < Model.Count; i++)
    {
        @Html.HiddenFor(m => m[i].ProjectAccessionNum)
        @Html.HiddenFor(m => m[i].ProjectNumber)
        @Html.HiddenFor(m => m[i].FieldStationCharge)
        @Html.HiddenFor(m => m[i].IsCurrentAd419Project)
    }
</form>