AD419.DataHelper.Web/Models/CfdaNumberImport.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace AD419.DataHelper.Web.Models
{
    [Table("CFDANumImport")]
    public partial class CfdaNumberImport
    {
        const string USDA = "Department of Agriculture";
        const string AD = "AGRICULTURE, DEPARTMENT OF"; // EndsWith
        const string NIFA = "National Institute of Food and Agriculture"; // StartsWith
        const string DHHS = "Department of Health and Human Services";
        const string HHSD = "HEALTH AND HUMAN SERVICES, DEPARTMENT OF"; // EndsWith
        const string NIH = "National Institutes of Health"; // StartsWith

        public CfdaNumberImport() { }
        public CfdaNumberImport(DataRow row)
        {
            Number = row["Program Number"].ToString();
            ProgramTitle = row["Program Title"].ToString();
            AgencyOffice = row["Federal Agency (030)"].ToString();
            Code = GetCode(AgencyOffice);
        }

        public int Id { get; set; }

        [Required]
        [Display(Name = "CFDA Number")]
        [StringLength(10)]
        [Column("CFDANum")]
        public string Number { get; set; }

        [Required]
        [Display(Name = "Program Title")]
        [StringLength(300)]
        public string ProgramTitle { get; set; }

        [Required]
        [Display(Name = "Agency/Office")]
        [StringLength(2048)]
        public string AgencyOffice { get; set; }

        [Display(Name = "Code")]
        [StringLength(10)]
        public string Code { get; set; }

        /// <summary>
        /// Sets the Code based of the Agency/Office for NIFA and NIH.
        /// </summary>
        /// <param name="agencyOffice"></param>
        private string GetCode(string agencyOffice)
        {
            if (string.IsNullOrEmpty(agencyOffice))
                return null;

            if (
                (agencyOffice.StartsWith(USDA, StringComparison.OrdinalIgnoreCase) && agencyOffice.IndexOf(NIFA, StringComparison.OrdinalIgnoreCase) > -1) || // Pre-SAMS
                (agencyOffice.EndsWith(AD, StringComparison.OrdinalIgnoreCase) && agencyOffice.StartsWith(NIFA, StringComparison.OrdinalIgnoreCase))          // Post-SAMS
            )
            {
                return "NIFA";
            }
            else if (
                (agencyOffice.StartsWith(DHHS, StringComparison.OrdinalIgnoreCase) && agencyOffice.IndexOf(NIH, StringComparison.OrdinalIgnoreCase) > -1) || // Pre-SAMS
                (agencyOffice.EndsWith(HHSD, StringComparison.OrdinalIgnoreCase) && agencyOffice.StartsWith(NIH, StringComparison.OrdinalIgnoreCase))        // Post-SAMS
            )
            {
                return "NIH";
            }

            return null;
        }
    }
}

AD419.DataHelper.Web/Controllers/CfdaNumberImportsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AD419.DataHelper.Web.Helpers;
using AD419.DataHelper.Web.Models;
using ExcelDataReader;

namespace AD419.DataHelper.Web.Controllers
{
    public class CfdaNumberImportsController : SuperController
    {
        // GET: CFDANumsImport
        public ActionResult Index()
        {
            return View(DbContext.CfdaNumberImports.ToList());
        }

        // GET: CFDANumsImport/Details/5
        public ActionResult Details(int id)
        {
            var num = DbContext.CfdaNumberImports.Find(id);
            if (num == null)
            {
                return HttpNotFound();
            }

            return View(num);
        }

        // GET: CFDANumsImport/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CFDANumsImport/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Number, ProgramTitle, AgencyOffice, Code")] CfdaNumberImport cfdaNumber)
        {
            if (!ModelState.IsValid) return View(cfdaNumber);

            DbContext.CfdaNumberImports.Add(cfdaNumber);
            DbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: CFDANumsImport/Edit/5
        public ActionResult Edit(int id)
        {
            var code = DbContext.CfdaNumberImports.Find(id);
            if (code == null)
            {
                return HttpNotFound();
            }

            return View(code);
        }

        // POST: CFDANumsImport/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Number, ProgramTitle, AgencyOffice, Code")] CfdaNumberImport cFdaNumberImport)
        {
            if (!ModelState.IsValid) return View(cFdaNumberImport);

            DbContext.Entry(cFdaNumberImport).State = EntityState.Modified;
            DbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: CFDANumsImport/Delete/5
        public ActionResult Delete(int id)
        {
            var num = DbContext.CfdaNumberImports.Find(id);
            if (num == null)
            {
                return HttpNotFound();
            }

            return View(num);
        }

        [HttpPost, ActionName("DeleteAll")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAll()
        {
            //This works but doesn't reset the sequence number.
            //var all = from c in db.CFDANumImport select c;
            //db.CFDANumImport.RemoveRange(all);
            //db.SaveChanges();

            DbContext.Database.ExecuteSqlCommand("TRUNCATE TABLE [dbo].[CFDANumImport]");

            AddNifaDefaultCfdaNum();

            return RedirectToAction("Index");
        }

        // POST: CFDANumsImport/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var num = DbContext.CfdaNumberImports.Find(id); if (num == null)
            {
                return HttpNotFound();
            }

            DbContext.CfdaNumberImports.Remove(num);
            DbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> file)
        {
            var myFile = Request.Files[0];
            if (myFile == null) return RedirectToAction("Index");

            var cfdaNums = new List<CfdaNumberImport>();
            var fileName = myFile.FileName;
            var excelReader = ExcelReaderFactory.CreateCsvReader(myFile.InputStream);

            var result = excelReader.AsDataSet(new ExcelDataSetConfiguration()
            {
                ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
                {
                    UseHeaderRow = true
                }
            });

            TempData.Add("Message", "Now viewing \"" + fileName + "\".");
            excelReader.Close();

            cfdaNums.AddRange(from DataRow row in result.Tables[0].Rows select new CfdaNumberImport(row));

            // This works.  Would now like the user to have a chance to review upload first.
            //if (ModelState.IsValid)
            //{
            //    db.CesListImports.AddRange(cesEntries);
            //    db.SaveChanges();
            //}

            return View("Display", cfdaNums);
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Save(List<CfdaNumberImport> cfdaNums)
        {
            if (cfdaNums != null)
            {
                // This works.  Would now like the user to have a chance to review upload first.
                if (ModelState.IsValid)
                {
                    DbContext.CfdaNumberImports.AddRange(cfdaNums);
                    DbContext.MarkStatusCompleted(ProcessStatuses.ImportCfdaNumbers);
                    DbContext.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }

        private void AddNifaDefaultCfdaNum()
        {
            var defaultNifaCfdaNum = new CfdaNumberImport()
            {
                AgencyOffice = "NATIONAL INSTITUTE OF FOOD AND AGRICULTURE, AGRICULTURE, DEPARTMENT OF",
                Number = "10.000", Code = "NIFA", ProgramTitle = "MISC ASSIGNED IN SPONSORED PROGRAMS"
            };
            DbContext.CfdaNumberImports.Add(defaultNifaCfdaNum);
            DbContext.SaveChanges();

        }
    }
}

AD419.DataHelper.Web/Views/CfdaNumberImports/Create.cshtml
@model AD419.DataHelper.Web.Models.CfdaNumberImport

@{
    ViewBag.Title = "Add CFDA Number";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create a new CFDA Number:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ProgramTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgencyOffice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgencyOffice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgencyOffice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AD419.DataHelper.Web/Views/CfdaNumberImports/Delete.cshtml
@model AD419.DataHelper.Web.Models.CfdaNumberImport

@{
    ViewBag.Title = "Delete CFDA Number";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CFDA Number @Html.DisplayFor(model => model.Number)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.ProgramTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyOffice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyOffice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AD419.DataHelper.Web/Views/CfdaNumberImports/Details.cshtml
@model AD419.DataHelper.Web.Models.CfdaNumberImport

@{
    ViewBag.Title = "CFDA Number Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>CFDA Number @Html.DisplayFor(model => model.Number):</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.ProgramTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyOffice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyOffice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AD419.DataHelper.Web/Views/CfdaNumberImports/Display.cshtml
@model System.Collections.Generic.List<AD419.DataHelper.Web.Models.CfdaNumberImport>

@{

    ViewBag.Title = "View CFDA Numbers Excel File";
}


<h2>@ViewBag.Title</h2>

@Styles.Render("~/Content/DataTables-1.9.4/media/css/dataTables")

@section AdditionalScripts
{
    @Scripts.Render("~/bundles/datatables")

    <script type="text/javascript">
        $(function () {
            var oTable = $(".table").dataTable({
                "oLanguage": {
                    "sLengthMenu": 'Display <select>' +
                        '<option value="10">10</option>' +
                        '<option value="25">25</option>' +
                        '<option value="50">50</option>' +
                        '<option value="100">100</option>' +
                        '<option value="-1">All</option>' +
                        '</select> records'
                },
                "iDisplayLength": -1,
                "aaSorting": [[0, "asc"]], //Default sort on second column
                //"aoColumnDefs": [
                //    //{ 'bSortable': false, 'aTargets': [0, 5] } //Disables sort on icon columns
                //]
            }).makeEditable();
            var oTable2 = $('#IndexTable').dataTable({
                "bSort": false,
                "bPaginate": false,
                "bInfo":false
            });
            var oTable3 = $('#ConstraintTable').dataTable({
                "bSort": false,
                "bPaginate": false,
                "bInfo": false
            });

        });
    </script>
}

@*<style type="text/css">
        .table {
            margin: 4px;
            border-collapse: collapse;
            width: 300px;
        }

        .header {
            background-color: gray;
            font-weight: bold;
            color: #fff;
        }

        .table th, .table td {
            border: 1px solid black;
            padding: 5px;
        }
    </style>*@

<div class="form-horizontal">
    @using (Html.BeginForm("Save", "CfdaNumberImports", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        for (var i = 0; i < Model.Count; i++)
        {
            @Html.HiddenFor(m => m[i].Number)
            @Html.HiddenFor(m => m[i].ProgramTitle)
            @Html.HiddenFor(m => m[i].AgencyOffice)
            @Html.HiddenFor(m => m[i].Code)
        }
        <br />
        <p>
            If all looks good, you can upload the values to the database.<br />
            <i>Note: You can also edit the values once they have been saved.</i>
        </p>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save CFDA Numbers to Database" class="btn btn-default" />
            </div>
        </div>
    }
</div>

<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m[0].Number)</th>
                <th>@Html.DisplayNameFor(m => m[0].ProgramTitle)</th>
                <th>@Html.DisplayNameFor(m => m[0].AgencyOffice)</th>
                <th>@Html.DisplayNameFor(m => m[0].Code)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Number</td>
                    <td>@item.ProgramTitle</td>
                    <td>@item.AgencyOffice</td>
                    <td>@item.Code</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="form-horizontal">
    @using (Html.BeginForm("Save", "CfdaNumberImports", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        for (var i = 0; i < Model.Count; i++)
        {
            @Html.HiddenFor(m => m[i].Number)
            @Html.HiddenFor(m => m[i].ProgramTitle)
            @Html.HiddenFor(m => m[i].AgencyOffice)
            @Html.HiddenFor(m => m[i].Code)
        }

        <p>
            If all looks good, you can upload the values to the database.<br />
            <i>Note: You can also edit the values once they have been saved.</i>
        </p>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save CFDA Numbers to Database" class="btn btn-default" />
            </div>
        </div>
    }
</div>

AD419.DataHelper.Web/Views/CfdaNumberImports/Edit.cshtml
@model AD419.DataHelper.Web.Models.CfdaNumberImport

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editing CFDA Number @Html.DisplayFor(model => model.Number):</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgencyOffice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgencyOffice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgencyOffice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AD419.DataHelper.Web/Views/CfdaNumberImports/Index.cshtml
@model IEnumerable<AD419.DataHelper.Web.Models.CfdaNumberImport>

@{
    ViewBag.Title = "Index - CFDA Numbers";
}

<div class="pull-right">
    <button class="btn btn-default display-inline" data-toggle="modal" data-target="#uploadModal"><i class="fa fa-upload"></i> Upload New Source File</button>
    <form action="@Url.Action("DeleteAll")" method="POST" class="display-inline">
        @Html.AntiForgeryToken()
        <input type="submit" id="btnDeleteAll" value="Delete All" title="Delete All" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete ALL the records?')"/>
    </form>
</div>

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Create New", "Create", "CfdaNumberImports", null, new { @class="btn btn-default" })
</p>

@if (Model.Count() != 0)
{
    <table id="cfdaImportTable" class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProgramTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AgencyOffice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProgramTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AgencyOffice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4>CFDA Numbers Data has yet to be created or uploaded.</h4>
    <p>Select the "Create New" (above) or browse and display an existing CFDA Numbers Excel file (above).</p>
}

@Html.Partial("_CfdaNumsUpload")

@section AdditionalScripts
{
    <script>
        $(function() {
            $('#cfdaImportTable').DataTable({
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
                columnDefs: [
                    { targets: [-1, -2, -3], sortable: false }
                ]
            });
        })
    </script>
}

AD419.DataHelper.Web/Views/CfdaNumberImports/_CfdaNumsUpload.cshtml
<div class="modal fade" id="uploadModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Upload a CFDA Numbers Excel file</h4>
            </div>
            <div class="modal-image">
                <img src="~/Content/Images/CFDANumsExample.PNG" alt="CFDA Num Excel upload file example">
            </div>
            @using (Html.BeginForm("Upload", "CfdaNumberImports", FormMethod.Post, new {id = "UploadForm", enctype = "multipart/form-data", @class = ""}))
            {
                <div class="modal-body">
                    <p>
                        Please ensure your spreadsheet has the column names as illustrated above.<br/>
                        Only the CFDANum, ProgramTitle, and Agency/Office columns are required.<br/>
                        Download a sample form <a href="~/Content/Sample_Forms/CfdaNumbersForImport.xlsx">HERE <i class="fa fa-download"></i></a>
                    </p>
                        <div class="form-group">
                            <label class="control-label">Please select an CFDA Numbers Excel file to display:</label>
                            <input type="file" id="FileUpload1" name="FileUpload1" class="" required/>
                        </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-default" value="Upload" />
                </div>
            }
        </div>
    </div>
</div>